---
# F5 Networks
# Ansible 101 Workshop - https://github.com/f5devcentral/FAS-ansible-workshop-101
# For more information on this class, please see the documentation
# at https://clouddocs.f5.com/training/fas-ansible-workshop-101/
- name: GRAB F5 FACTS
  hosts: f5
  connection: local
  gather_facts: no

  tasks:
  
    - set_fact:
       provider:
        server: "{{private_ip}}"
        user: "{{ansible_user}}"
        password: "{{ansible_ssh_pass}}"
        server_port: 8443
        validate_certs: no
    
    - name: COLLECT BIG-IP FACTS
      bigip_device_info:
        gather_subset:
         - system-info
        provider: "{{provider}}"
      register: device_facts

    - name: DISPLAY COMPLETE BIG-IP SYSTEM INFORMATION
      debug:
        var: device_facts

    - name: DISPLAY ONLY THE MAC ADDRESS
      debug:
        var: device_facts['system_info']['base_mac_address']

    - name: DISPLAY ONLY THE VERSION
      debug:
        var: device_facts['system_info']['product_version']
