---
# F5 Networks
# Ansible 101 Workshop - https://github.com/f5devcentral/FAS-ansible-workshop-101
# For more information on this class, please see the documentation
# at https://clouddocs.f5.com/training/fas-ansible-workshop-101/
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  vars:
  irules: ['irule1','irule2']
  
  tasks:

  - set_fact:
    provider:
      server: "{{private_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: 8443
      validate_certs: no
      
  - name: ADD iRules
    bigip_irule:
      provider: "{{provider}}"
      module: "ltm"
      name: "{{item}}"
      content: "{{lookup('file','{{item}}')}}"
    with_items: "{{irules}}"
    
  - name: ATTACH iRules TO VIRTUAL SERVER
    bigip_virtual_server:
      provider: "{{provider}}"
      name: "vip"
      irules: "{{irules}}"
