---
# F5 Networks
# Ansible 101 Workshop - https://github.com/f5devcentral/FAS-ansible-workshop-101
# For more information on this class, please see the documentation
# at https://clouddocs.f5.com/training/fas-ansible-workshop-101/
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  vars_files:
    virtuals_pools.yml

  tasks:

  - set_fact:
     provider:
      server: "{{private_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: 8443
      validate_certs: no
        
  - name: CREATE POOL
    bigip_pool:
      provider: "{{provider}}"
      name: "{{item.pool_name}}"
      lb_method: "round-robin"
      monitors: "/Common/http"
      monitor_type: "and_list"
    loop: "{{vips_pools}}"

